datasetpath: '/home/aneesh/Desktop/Datasets/RSNA'
picklefile: '/home/aneesh/Desktop/Datasets/RSNA/pd_sheet.pkl'
epochs: 5
batch_size: 40
lr: 0.0002
momentum: 0.9
beta1: 0.9
beta2: 0.999
optimizer: adam
network: resnet50
pretrained_flag: True
model_name: resnet50
