datasetpath: '/home/aneesh/Desktop/Datasets/RSNA'
picklefile: '/home/aneesh/Desktop/Datasets/RSNA/pd_sheet.pkl'
epochs: 5
batch_size: 40
lr: 0.0002
momentum: 0.9
beta1: 0.5
beta2: 0.999
optimizer: adam
network: dilatedresnet50
pretrained_flag: False
model_name: dilatedr50_scratch
