datasetpath: '/home/aneesh/Desktop/Datasets/RSNA'
picklefile: '/home/aneesh/Desktop/Datasets/RSNA/pd_sheet.pkl'
epochs: 3
batch_size: 128
lr: 0.0005
momentum: 0.9
beta1: 0.9
beta2: 0.999
optimizer: adam
network: resnext50
pretrained_flag: True
model_name: resnext50
